# Generated by Django 5.0.3 on 2024-04-04 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 8, 42, 56, 372021, tzinfo=datetime.timezone.utc)),
        ),
    ]
