# Generated by Django 5.0.3 on 2024-04-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
